title: Ivan Farhan Amien # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Ivan Farhan Amien. I am currently pursuing a Business Information & Technology bachelor's at BINUS University, where I have learned Information Systems Analyis and Design, Database, Basic Programming, Application Development, Business Intelligence, and Business Analytics. I am proficient in User Experience design using Axure, creating diagrams in Visual Paradigm, and system analysis. I am currently focusing on learning data visualization using TIBCO Spotfire and Microsoft Excel. I am interested in working in UX design, business analytics, and data analytics to futher improve my proficiency in these areas. 
  <br><br>
  I am able to work in a team environment and individually. I Have a strong sense of responsibility and team work. I am eager to constantly grow professionally and to learn and develop skills. I Strive to give the best results for every work.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
