title: Ivan Farhan Amien 
logo: "/images/avatar.png?raw=true" 
description:
  <p align="justify">
  I am currently pursuing a Business Information & Technology bachelor's at BINUS University, where I have learned Information Systems, Andoird App Development, and Business Intelligence. I am proficient in UX design using Axure, creating diagrams in Visual Paradigm, and system analysis. I am interested in working in UX design, business analytics, and data analytics to futher improve my proficiency in these areas. 
  <br><br>
  I am able to work in a team environment and individually. I Have a strong sense of responsibility and team work. I am eager to constantly grow professionally and to learn and develop skills. I Strive to give the best results for every work.
  <br><br>
  <a href="https://www.linkedin.com/in/ivan-amien-239923128//">View my LinkedIn</a> 
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
